### ISSUE TITLE
Master Mode/One hit obliterator objects cannot be hidden

### ISSUE THREAD

**Issue by iTNTPiston** [zeldamods/objmap#21]
Toggling the Master Mode or One Hit Obliterator switch has no effect. The actors are always shown.

**Comment by leoetlino** [comment]
Yes, the master mode switch has no effect on searches. It only controls whether enemies are ranked up. I guess we should probably hide master mode results when the switch is off?

**Comment by iTNTPiston** [comment]
The current description for the master mode switch is "If enabled, show Master Mode only objects and automatically rank up enemies. Note: this does not affect search." It's misleading if master mode only objects are also shown when disabled.

**Comment by leoetlino** [comment]
So I tried to reproduce it but I couldn't manage to. For search groups that have been added to the map, Master Mode objects (e.g. Sky Octoroks) do disappear when the master mode toggle is off and reappear when it's switched on.

However, as stated in the description, this does not affect search results (represented by red circles) until they are added to the map.
