### ISSUE TITLE
Add colorpicking to the map markers

### ISSUE THREAD

**Issue by vladisvrau** [zeldamods/objmap#47]
Currently the map marker is a static png file and it would be cool to be able to pick the color of the markers for routing purposes and stuff

**Comment by savage13** [comment]
Does this work?  The marker is a snippet of SVG that matches the existing leaflet markers.

![Screen Shot 2021-11-28 at 2 17 20 PM](https://user-images.githubusercontent.com/126514/143782623-e158961e-6f7b-4d78-9893-7d65509dfd5b.png)

**Comment by savage13** [comment]
Update, got it working on the objma

![Screen Shot 2021-11-28 at 4 38 21 PM](https://user-images.githubusercontent.com/126514/143787027-279c581b-8442-4b18-9aee-6b78b722857f.png)
p.

**Comment by vladisvrau** [comment]
Hell yeah, this is perfect

**Comment by savage13** [comment]
This should be resolved by
pr #58
