### ISSUE TITLE
Drawing tool confirm clear all

### ISSUE THREAD

**Issue by savage13** [zeldamods/objmap#50]
The drawing tool’s clear all function would benefit from a confirmation dialog.

see https://discord.com/channels/269611402854006785/269611402854006785/902939500286722068

**Comment by iTNTPiston** [comment]
Found a bug for this **savage13:delete_confirm**
Click delete icon -> delete something -> save
Get's the "clear all?" confirmation (should be no confirmation dialog)

**Comment by savage13** [comment]
The save button emits a `draw:deleted` action.

If the Leaflet-draw `drawLayer` has **nothing** on it and the layer sent with the emitted action is **not empty** we can assume that the **"Clear All"** button was called.

If the Leaflet-draw `drawLayer` has **something** on it and the layer sent with the emitted action is **empty or has something** we can assume that the **"Save"** button was called.

**Comment by leoetlino** [comment]
That sounds like a sane way to check for "clear all".
