### ISSUE TITLE
Performance investigation for color picker

### ISSUE THREAD

**Issue by iTNTPiston** [zeldamods/objmap#54]
The color picker is quite laggy. I wonder if there's any unnecessary updates going on? Ideally we should update once when the color picking is done

**Comment by savage13** [comment]
Looks like changing the color calls `L.Control.Draw.setDrawingOptions()`.  

The example at https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input/color works fine.

**Comment by savage13** [comment]
Looking more into this. The use of `v-model` on the `<input type="color">` watches for `input` events then does a number of calculations causing delay, ~20ms per event.  Replacing `v-model` with `@input="drawOnColorChange"`fixes the delay, with <0.1ms per event.
