### ISSUE TITLE
Add Korok IDs

### ISSUE THREAD

**Issue by savage13** [zeldamods/objmap#55]
There is a set of Korok IDs used in routing, it would be useful to include these on the map somehow.

Options:
- As tooltips only shown on mouseover
- As persistent tooltips, controlled by a toggle
- Within the `objs` table as a new column or in the `data` column
   -  This would make the specific Koroks searchable

Map with Korok IDs
https://drive.google.com/file/d/1_yJsYytNQ7spQHKPpiXeoing2Voo8uuD/view

**Comment by savage13** [comment]
Below is an example of what I am thinking of:

- Korok IDs can be shown as either a 
- 1) tooltip (on mouseover) or 
- 2) always displayed
controlled by the "Show Korok IDs".  

The color and style of the tooltips matches the original Korok ID map.   The one think I do not like is none of the Korok Tooltips say "Korok", but maybe that is implied by the Korok seed icon and the label that says "Korok".

Still looking into inserting the Korok ID into the table (probably as a new column).

![Screenshot 2021-11-09 at 18-33-13 BotW Object Map](https://user-images.githubusercontent.com/126514/141022573-fbd71b91-fdd9-4cee-8fec-3487a5c8afc5.png)

**Comment by leoetlino** [comment]
IMO adding "Korok" to the tooltips would significantly reduce map legibility. The tooltips already overlap in places with high Korok seed density and making the tooltip labels longer would only make it worse.
