### ISSUE TITLE
ID List

### ISSUE THREAD

**Issue by creationstation-source** [zeldamods/objmap#66]
Hello creators of this mod, I have a question that regards the # ID's of this mod, whenever I search for anything using this application, I noticed that everything has an # ID. Is there a way to find the complete list of every # ID in this application somewhere in the coding? or otherwise by entering a command in the in-application search bar?

**Comment by leoetlino** [comment]
No, that's not possible.

Write a script to parse the game's map files (https://github.com/leoetlino/botw/tree/master/Map) if you need all the IDs.
