### ISSUE TITLE
 Feature Request, please make a release for offline use

### ISSUE THREAD

**Issue by RXElier** [zeldamods/objmap#95]
I would like to ask you to please make a version so that we can use your incredibly wonderful work in an offline way so that when we are traveling or isolated where we cannot connect we can use it

**Comment by leoetlino** [comment]
Here's a very old (March 2019) offline version of the object map: https://static.zeldamods.org/objmap-offline.7z (313MB compressed, ~600MB decompressed)

Extract the archive, open the executable and point your browser to http://localhost:3007/

It doesn't have the latest features, but this is probably good enough for offline use.

**Comment by RXElier** [comment]
> Here's a very old (March 2019) offline version of the object map: https://static.zeldamods.org/objmap-offline.7z (313MB compressed, ~600MB decompressed)
> 
> Extract the archive, open the executable and point your browser to http://localhost:3007/
> 
> It doesn't have the latest features, but this is probably good enough for offline use.

this is enough for me, thank you very much

**Comment by hgh32** [comment]
> Here's a very old (March 2019) offline version of the object map: https://static.zeldamods.org/objmap-offline.7z (313MB compressed, ~600MB decompressed)
> 
> Extract the archive, open the executable and point your browser to http://localhost:3007/
> 
> It doesn't have the latest features, but this is probably good enough for offline use.

Is this a compiled version of radar?
How can I compile the latest version of it?

**Comment by hgh32** [comment]
> 

It took me a while to understand how objmap and radar interact
They seem to need two localhost addresses for offline use
How did you compile them to only need objmap localhost?

**Comment by hgh32** [comment]
> It's a modified version of Radar with a server that also serves the object map assets.
> 
> I don't remember what I used to create the .exe. Maybe [nexe](https://github.com/nexe/nexe)?

It took me a while to understand how objmap and radar interact
They seem to need two localhost addresses for offline use
How did you compile them to only need objmap localhost?

**Comment by leoetlino** [comment]
As I mentioned previously, Radar's web server was modified to also serve the object map frontend application, so only one web server is required.

**Comment by RXElier** [comment]
> > It's a modified version of Radar with a server that also serves the object map assets.
> > I don't remember what I used to create the .exe. Maybe [nexe](https://github.com/nexe/nexe)?
> 
> It took me a while to understand how objmap and radar interact They seem to need two localhost addresses for offline use How did you compile them to only need objmap localhost?

If you find a way to compile it for offline use could you please share with me, I still don't have the knowledge to do it myself.
